# the compiler: gcc for C program, define as g++ for C++
CC = g++

# compiler flags:
#  -g    adds debugging information to the executable file
#  -Wall turns on most, but not all, compiler warnings
CFLAGS  = -Wall


main:
	$(CC) $(CFLAGS) main.cpp -o main.out

clean:
	rm *.out